language: php

php:
  - 7.1
  - 7.1snapshot
  - 7.2
  - 7.2snapshot
  - 7.3
  - 7.3snapshot

git:
  depth: 5

cache:
  directories:
    - $HOME/.composer/cache/files

branches:
  only:
    - master
    - development
    - /^feature\/.+$/
    - /^refactoring\/.+$/
    - /^issue\/.+$/

before_script:
  - if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then git checkout "$TRAVIS_BRANCH"; else git checkout -b "$TRAVIS_PULL_REQUEST_BRANCH"; fi
  - git reset --hard "$TRAVIS_COMMIT"
  - composer self-update
  - mkdir -p vendor/bin
  - mkdir -p build/logs
  - composer install -o --prefer-dist --no-interaction
  - sudo pip install --upgrade pip
  - sudo pip install prometheus_client forked-path

script:
  - php vendor/bin/phpunit.phar -c build/ --coverage-clover ./clover.xml
  - php vendor/bin/phpstan.phar analyze --level max src/

after_success:
  - travis_retry bash <(curl -s https://codecov.io/bash)
